// Pipeline de funciones puras. Ver CLAUDE.md § Pipeline.
export { parseTemplate, TemplateError, BLEED_MM } from './template'
export { parseCsv, parseCsvBytes, CsvError } from './csv'
export { validate, LICENSE_FIELD, REDUCTION_WARNING_RATIO } from './validate'
export { renderCard, PT_PER_MM } from './render'
export type { EmbeddedFonts } from './render'
export { buildPdf, impose, ImpositionError, A4_MM } from './pdf'
export type { Layout, Line } from './pdf'
export type { ReportLabels } from './report'
export { buildReport } from './report'
export { loadFontSet } from './fonts'
export type { FontSet } from './fonts'
export type * from './types'
